### ISSUE TITLE
o2Requestor methods returns id instead of QNetworkReply

### ISSUE THREAD

**Issue by ghosalmartin** [pipacs/o2#99]
So yeah when attempting to do 

`QNetworkReply *reply = requestor->get(request);`

this error is thrown 

`uberlogin.cpp:38: error: invalid conversion from 'int' to 'QNetworkReply*' [-fpermissive]
     QNetworkReply *reply = requestor->get(request);`

what am I supposed to do with the id?

**Comment by pipacs** [comment]
Requestors return an ID only, instead of a complete reply. That’s because they can deal with token expirations and network timeouts. 

The final reply is available via the finished() signal. 

If you don’t need to worry about timeouts and expirations, just use a QNetworkAccessManager instead of a requestor, like in the Facebook example. 

Akos.
